{% set name = "trame-simput" %}
{% set version = "2.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b3a43eeddcf3d2eb2874b2a953c42e5cb7dc6e80464b9538cb600a4912de847d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/trame-simput/
  summary: Simput implementation for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - jourdain
    - psavery
    - kwrobot
