{% set name = "trame-simput" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trame-simput-{{ version }}.tar.gz
  sha256: 218aa52c32de8c6eca0277fdf1b2195f65b2501d5b5a2fd9923a7b4a5bacdcdc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pyyaml
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-simput/
  summary: Simput implementation for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
