{% set name = "trame-simput" %}
{% set version = "2.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 46680435c07fb93487c97251df1000c4395ea24208fb7a0ec311bb8e7e224f64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/trame-simput/
  summary: Simput implementation for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
